### ISSUE TITLE
システムコール-エラー対応方針決定

### ISSUE THREAD

**Issue by YungTatyu** [YungTatyu/webserv#108]
# 内容
- システムコール失敗時の対応を決める
  - 失敗すると致命的な場合
    - i/o多重化api
       - polling api
    - server init api
      - socket, bind,  listen
  - それ以外など 
    - accept

### 追記：
polling apiのシステムコールのみ対応。

- select, poll 
-> wait系のシステムコール時にメモリ確保するので、そのタイミングでENOMEMが起こりうる。
起こったら、timeoutが一番近いclientから削除していく。削除するclientがなくなったらpollingし続ける。

- epoll, kqueue
-> epoll_ctlやイベント登録時のkeventでENOMEMが起こりうる。起こるのはおそらく新しくイベントを追加するときだけなので、acceptした後のaddNewEventが失敗したときのみ、そのクライアントとの接続を切る。

**Comment by ayase-mstk** [comment]
kqueue runtime_error

kqueue:
既に対応済みだが、失敗したらサーバー落とす。
>[ENOMEM] The kernel failed to allocate enough memory for  the kernel queue.
[ENOMEM]  The RLIMIT_KQUEUES rlimit (see getrlimit(2)) for the current user would be	exceeded.
[EMFILE] The per-process descriptor table is full.
[ENFILE] The system file table	is full.

kevent:
keventに渡す構造体も初期化してから渡すようにしましょう。
以下のエラーについて、epoll_ctlと同様に対応する必要がある。
イベント待機中のほうのkeventではまた別の対策が必要かもしれない。（再試行のみなど）
>[ENOMEM] No memory was available to register the event or, in the  special case of a timer, the maximum number of timers has been exceeded.  This maximum  is  configurable via the kern.kq_calloutmax sysctl.

**Comment by ayase-mstk** [comment]
poll runtime_error


poll
EINVALに関してはRLIMIT_NOFILEを超えたｆｄが登録される前にacceptが失敗するはずなので超えることはないと思います。
よって起こるとしたらENOMEMで、これも少し間をおいて再試行するなどがいいと思います。そして規定回数失敗したらサーバーが落ちるのもや無負えないとおもいます。
> EINVAL The nfds value exceeds the RLIMIT_NOFILE value.
ENOMEM -> Unable to allocate memory for kernel data structures.

**Comment by ayase-mstk** [comment]
select runtime_error

selectに関してはすべてロジックエラーだと思うので、特に対応する必要はないと思います。
