### ISSUE TITLE
サーバーのインターフェースデータ構造設計

### ISSUE THREAD

**Issue by kohshi54** [YungTatyu/webserv#16]

**Comment by ayase-mstk** [comment]
epoll
Linux系のOSに備わっているイベント通知インターフェース
監視したいイベントをepoll_ctl()で登録しておけば、そのイベントが完了したときにepoll_wait()で通知を受け取れる。

**Comment by ayase-mstk** [comment]
kqueue

**Comment by ayase-mstk** [comment]
共通項
select , epoll, kqueueのinterfaceをつくって、それぞれ必要なものは継承クラスで追加する感じ

listen portの集合ー＞std::vectorに追加する

**Comment by ayase-mstk** [comment]
select
